# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d4c43b05190ed03784a88bbed5c2bc7aca382318cd4418dfc4c5763b85782954b2187e9bd2dd5ae44108bb87adc2d4c65b01764e5b42da9db38f03fbc37c9c

test:
  secret_key_base: 55c4b004036efc1f68c4bd78acd3729e705911be2f7685667d053ef0ff3c1c1e4160018e4176e1cb960c58675e08f542b77597a2c10553c27cf5d2936a29fda9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
